#!/usr/bin/env python3
"""Rewrite the primary nav and mobile drawer links on the hand written pages
so they match the shared mega menu markup in nav_menu.py. Safe to re-run.

    python3 scripts/apply_nav.py

Service sub pages are generated by build_subpages.py, which uses the same module.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import nav_menu  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

# file -> (page key for aria-current, contact link)
PAGES = {
    "index.html": ("home", "#contact"),
    "services.html": ("residential", "index.html#contact"),
    "commercial.html": ("commercial", "index.html#contact"),
    "tankless.html": ("tankless", "index.html#contact"),
    "financing.html": ("financing", "index.html#contact"),
    "story.html": ("story", "index.html#contact"),
}

PRIMARY = re.compile(r'(<nav class="nav__links" aria-label="Primary">\n).*?(\n    </nav>)', re.S)
MOBILE = re.compile(r'(<nav aria-label="Mobile">\n).*?(\n  </nav>)', re.S)


def main():
    for name, (key, contact) in PAGES.items():
        path = ROOT / name
        html = path.read_text(encoding="utf-8")
        desktop = nav_menu.desktop_links(active=key if key in nav_menu.MENUS else None,
                                         current_page=key, contact_href=contact)
        drawer = nav_menu.drawer_links(active=key if key in nav_menu.MENUS else None,
                                       current_page=key, contact_href=contact)
        html, n1 = PRIMARY.subn(lambda m: m.group(1) + desktop + m.group(2), html, count=1)
        html, n2 = MOBILE.subn(lambda m: m.group(1) + drawer + m.group(2), html, count=1)
        if n1 != 1 or n2 != 1:
            sys.exit(f"{name}: nav blocks not found (primary={n1}, mobile={n2})")
        path.write_text(html, encoding="utf-8")
        print(f"patched {name}")


if __name__ == "__main__":
    main()
