#!/usr/bin/env python3
"""Build the residential and commercial service sub pages.

Every sub page is generated from data/subpages.json, which also holds the
single shared list of Unsplash images. Edit the JSON, then run:

    python3 scripts/build_subpages.py

The pages are written as plain static HTML next to index.html so they
share styles.css and main.js with the rest of the site.
"""
import json
import sys
from html import escape
from urllib.parse import quote_plus
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "subpages.json"
SITE = "https://www.mrplumberinc.com"
CSS_VER = "20261007g"
JS_VER = "20261007g"
UTM = "utm_source=mr_plumber&amp;utm_medium=referral"

PHONE_SVG = ('<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 10.8a15.1 15.1 0 0 0 6.6 6.6l2.2-2.2c.3-.3.7-.4 1-.2 '
             '1.2.4 2.4.6 3.6.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1A17 17 0 0 1 3 4c0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.5.6 '
             '3.6.1.4 0 .8-.2 1l-2.3 2.2z"/></svg>')

SECTIONS = {
    "residential": {"label": "Residential", "href": "services.html", "nav": "Residential"},
    "commercial": {"label": "Commercial", "href": "commercial.html", "nav": "Commercial"},
}

WHY = {
    "residential": [
        ("Family owned since 1958", "The same family, in the same trade, for four generations."),
        ("Licensed, bonded and insured", "Work done to code by a company that stands behind it."),
        ("24/7 emergency line", "Call 803-600-4357 when something can't wait."),
        ("Authorized Rinnai dealer", "Tankless water heaters installed and serviced by the people who know them."),
        ("Financing available", "Through Wells Fargo and Synchrony on water heaters, repipes and other larger jobs."),
        ("Serving the Midlands", "Columbia, Lexington, Irmo, Orangeburg and the surrounding areas."),
    ],
    "commercial": [
        ("Family owned since 1958", "Four generations serving the businesses of Columbia and the Midlands."),
        ("Licensed, bonded and insured", "Work done to code by a company that stands behind it."),
        ("Priority scheduling", "Account holders move to the front of the line when something breaks."),
        ("Third-party billing", "We can invoice the manager or maintenance company, not the owner."),
        ("Updates from the field", "We keep you posted while the tech is still on site."),
        ("Clean paperwork", "Invoices and documentation formatted to match your approval process."),
    ],
}

INDUSTRIES = ["Restaurants", "Motels & hotels", "Property managers", "Facility maintenance companies",
              "Churches & schools", "Retail & office buildings", "Industrial facilities"]


def e(text):
    return escape(text, quote=True)


def img_url(pid, w, h=None, q=80):
    size = f"&amp;h={h}" if h else ""
    return f"https://images.unsplash.com/{pid}?w={w}{size}&amp;q={q}&amp;auto=format&amp;fit=crop"


def quote_href(page, need=None):
    href = f"index.html?service={page['service']}"
    if need:
        href += "&amp;need=" + quote_plus(need)
    return href + "#contact"


def head(page):
    url = f"{SITE}/{page['slug']}.html"
    sec = SECTIONS[page["section"]]
    crumbs = json.dumps({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": sec["label"], "item": f"{SITE}/{sec['href']}"},
            {"@type": "ListItem", "position": 3, "name": page["name"], "item": url},
        ],
    }, indent=2)
    service = json.dumps({
        "@context": "https://schema.org",
        "@type": "Service",
        "serviceType": page["name"],
        "provider": {"@type": "Plumber", "name": "Mr. Plumber, Inc.", "telephone": "+1-803-600-4357", "url": f"{SITE}/"},
        "areaServed": {"@type": "AdministrativeArea", "name": "The Midlands, South Carolina"},
        "hasOfferCatalog": {
            "@type": "OfferCatalog",
            "name": page["name"],
            "itemListElement": [{"@type": "Offer", "itemOffered": {"@type": "Service", "name": c["title"]}} for c in page["cards"]],
        },
    }, indent=2)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Generated by scripts/build_subpages.py from data/subpages.json. Edit the data file, not this page. -->
<title>{e(page['meta_title'])}</title>
<meta name="description" content="{e(page['meta_description'])}">
<meta name="theme-color" content="#1F2D3A">
<link rel="canonical" href="{url}">
<link rel="icon" href="assets/favicon.ico" sizes="any">
<link rel="icon" href="assets/favicon-512.png" type="image/png" sizes="512x512">
<link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Mr. Plumber, Inc.">
<meta property="og:title" content="{e(page['meta_title'])}">
<meta property="og:description" content="{e(page['meta_description'])}">
<meta property="og:url" content="{url}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@600;700;800&family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css?v={CSS_VER}">

<script type="application/ld+json">
{crumbs}
</script>
<script type="application/ld+json">
{service}
</script>
</head>"""


def nav(section):
    def link(href, label, key=None):
        current = ' aria-current="page"' if key == section else ""
        return f'      <a href="{href}"{current}>{label}</a>'
    links = "\n".join([
        link("index.html", "Home"),
        link("services.html", "Residential", "residential"),
        link("commercial.html", "Commercial", "commercial"),
        link("tankless.html", "Tankless"),
        link("financing.html", "Financing"),
        link("story.html", "Our Story"),
        link("index.html#contact", "Contact"),
    ])
    return f"""<body class="page-fade">
<a class="skip" href="#main">Skip to content</a>

<header class="nav" id="nav">
  <div class="nav__inner">
    <a class="brand" href="./" aria-label="Mr. Plumber, Inc. home">
      <span class="brand__mark"><img src="assets/logo.png" alt="Mr. Plumber, Inc." width="1100" height="333"></span>
    </a>
    <nav class="nav__links" aria-label="Primary">
{links}
    </nav>
    <div class="nav__actions">
      <a class="btn btn--brick btn--sm navphone" href="tel:18036004357">
        {PHONE_SVG}
        <span class="navphone__stack">
          <span class="navphone__tag">Emergency?</span>
          <span class="navphone__num">803-600-4357</span>
        </span>
      </a>
      <a class="btn btn--brick btn--sm navcontact" href="index.html#contact">Contact</a>
      <button class="burger" id="burger" aria-label="Open menu" aria-expanded="false" aria-controls="drawer">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</header>

<div class="drawer" id="drawer" hidden>
  <nav aria-label="Mobile">
    <a href="index.html">Home</a>
    <a href="services.html">Residential Services</a>
    <a href="commercial.html">Commercial Services</a>
    <a href="tankless.html">Tankless Water Heaters</a>
    <a href="financing.html">Financing</a>
    <a href="story.html">Our Story</a>
    <a href="index.html#contact">Contact</a>
    <a href="https://gotanklesssc.com/" target="_blank" rel="noopener">Go Tankless SC</a>
  </nav>
  <a class="btn btn--brick btn--block drawer__call" href="tel:18036004357">
    <span class="navphone__tag">Emergency?</span>
    <span class="navphone__num">Call 803-600-4357</span>
  </a>
  <p class="drawer__note">For plumbing emergencies, call us directly</p>
</div>
"""


def hero(page):
    sec = SECTIONS[page["section"]]
    pid = page["hero_img"]
    return f"""
<section class="subhero subhero--photo">
  <div class="subhero__bg" aria-hidden="true">
    <img src="{img_url(pid, 1920)}"
         srcset="{img_url(pid, 1100)} 1100w, {img_url(pid, 1920)} 1920w"
         sizes="100vw" alt="" fetchpriority="high" decoding="async">
  </div>
  <div class="subhero__scrim" aria-hidden="true"></div>
  <div class="subhero__inner">
    <nav class="crumb reveal" aria-label="Breadcrumb">
      <a href="./">Home</a> <span aria-hidden="true">/</span>
      <a href="{sec['href']}">{sec['label']}</a> <span aria-hidden="true">/</span>
      <span aria-current="page">{e(page['name'])}</span>
    </nav>
    <h1 class="reveal" style="--d:.06s">{e(page['name'])}</h1>
    <p class="subhero__sub reveal" style="--d:.12s">{e(page['summary'])}</p>
    <div class="subhero__cta reveal" style="--d:.18s">
      <a class="btn btn--brick btn--lg" href="{quote_href(page)}">Get a Quote</a>
      <a class="btn btn--glass btn--lg" href="tel:18036004357">
        {PHONE_SVG}
        <span>Call 803-600-4357</span>
      </a>
    </div>
  </div>
</section>
"""


def intro(page):
    signs = "".join(f"<li>{e(s)}</li>" for s in page["intro_signs"])
    return f"""
<section class="sec sec--tight">
  <div class="wrap">
    <div class="sp-intro">
      <article class="sp-intro__col reveal" style="--d:.03s">
        <p class="eyebrow"><span class="eyebrow__rule"></span>What It Is</p>
        <p>{e(page['intro_what'])}</p>
      </article>
      <article class="sp-intro__col reveal" style="--d:.08s">
        <p class="eyebrow"><span class="eyebrow__rule"></span>Signs You Need It</p>
        <ul class="sp-list">{signs}</ul>
      </article>
      <article class="sp-intro__col reveal" style="--d:.13s">
        <p class="eyebrow"><span class="eyebrow__rule"></span>What To Expect</p>
        <p>{e(page['intro_expect'])}</p>
      </article>
    </div>
  </div>
</section>
"""


def card(page, c, i, images):
    pid = c["img"]
    alt = images[pid]["alt"]
    inc = "".join(f"<li>{e(x)}</li>" for x in c["included"])
    sig = "".join(f"<li>{e(x)}</li>" for x in c["signs"])
    return f"""    <li class="scard scard--sub reveal" style="--d:{0.03 * (i % 3 + 1):.2f}s">
      <img class="scard__img" src="{img_url(pid, 800, 450)}" srcset="{img_url(pid, 480, 270)} 480w, {img_url(pid, 800, 450)} 800w" sizes="(max-width:640px) 100vw, (max-width:960px) 50vw, 380px" alt="{e(alt)}" width="800" height="450" loading="lazy" decoding="async">
      <div class="scard__body">
        <h3 class="scard__title">{e(c['title'])}</h3>
        <p class="scard__desc">{e(c['desc'])}</p>
        <hr class="scard__rule">
        <p class="scard__label">What's included</p>
        <ul class="scard__list scard__list--inc">{inc}</ul>
        <p class="scard__label">Common signs you need this</p>
        <ul class="scard__list scard__list--sign">{sig}</ul>
        <div class="scard__actions scard__actions--one">
          <a class="btn btn--brick btn--sm" href="{quote_href(page, c['title'])}" aria-label="Get a quote for {e(c['title'])}">Get a Quote</a>
        </div>
      </div>
    </li>"""


def credits(page, images):
    people = []
    for name, user in [page["hero_credit"]] + [(images[c["img"]]["name"], images[c["img"]]["user"]) for c in page["cards"]]:
        if (name, user) not in people:
            people.append((name, user))
    links = ", ".join(f'<a href="https://unsplash.com/@{u}?{UTM}" target="_blank" rel="noopener">{e(n)}</a>' for n, u in people)
    return f'    <p class="scard-credits">Photos: {links} on <a href="https://unsplash.com/?{UTM}" target="_blank" rel="noopener">Unsplash</a></p>'


def grid(page, images):
    cards = "\n".join(card(page, c, i, images) for i, c in enumerate(page["cards"]))
    noun = SECTIONS[page["section"]]["label"]
    return f"""
<section class="sec">
  <div class="wrap">
    <header class="sec__head sec__head--center reveal">
      <p class="eyebrow"><span class="eyebrow__rule"></span>{noun} Services</p>
      <h2 class="h2">What We Handle</h2>
    </header>
    <ul class="scard-grid{' scard-grid--four' if len(page['cards']) == 4 else ''}">
{cards}
    </ul>
{credits(page, images)}
  </div>
</section>
"""


def industries(page):
    if page["section"] != "commercial":
        return ""
    chips = "".join(f"<li>{e(x)}</li>" for x in INDUSTRIES)
    return f"""
<section class="sec sec--tight">
  <div class="wrap">
    <header class="sec__head sec__head--center reveal">
      <p class="eyebrow"><span class="eyebrow__rule"></span>Who We Serve</p>
      <h2 class="h2 h2--sm">Industries We Work With</h2>
    </header>
    <ul class="chips chips--center reveal">{chips}</ul>
  </div>
</section>
"""


def why(page):
    items = "".join(
        f'<li class="sp-why__item"><strong>{e(t)}</strong><span>{e(d)}</span></li>' for t, d in WHY[page["section"]]
    )
    return f"""
<section class="sec sec--midlands sec--tight">
  <div class="wrap">
    <header class="sec__head sec__head--center reveal">
      <p class="eyebrow"><span class="eyebrow__rule"></span>Why Mr. Plumber</p>
      <h2 class="h2 h2--sm">Four Generations Of Trust In The Midlands</h2>
    </header>
    <ul class="sp-why reveal">{items}</ul>
  </div>
</section>
"""


def cta(page):
    return f"""
<section class="sec sec--contact">
  <div class="wrap">
    <header class="sec__head sec__head--center reveal">
      <p class="eyebrow eyebrow--light"><span class="eyebrow__rule"></span>Get In Touch</p>
      <h2 class="h2 h2--light">Ready For Reliable Plumbing?</h2>
      <p class="lede lede--light" style="margin-inline:auto">
        Tell us what's going on and we'll get back to you, usually the same
        business day. For anything urgent, give us a call.
      </p>
      <div class="review__links">
        <a class="btn btn--glass btn--lg lift lift--sm" href="tel:18036004357">Call 803-600-4357</a>
        <a class="btn btn--brick btn--lg lift lift--sm" href="{quote_href(page)}">Get a Quote</a>
      </div>
    </header>
  </div>
</section>
"""


FOOTER = """
<footer class="foot">
  <div class="wrap">
    <div class="foot__top">
      <div class="foot__brand">
        <span class="foot__logo"><img src="assets/logo.png" alt="Mr. Plumber, Inc." width="1100" height="333"></span>
        <p class="foot__tag">Four Generations, One Commitment To Quality.</p>
      </div>
      <nav class="foot__nav" aria-label="Footer">
        <a href="./">Home</a>
        <a href="services.html">Residential Services</a>
        <a href="commercial.html">Commercial Services</a>
        <a href="tankless.html">Tankless Water Heaters</a>
        <a href="financing.html">Financing</a>
        <a href="story.html">Our Story</a>
        <a href="index.html#contact">Contact</a>
        <a href="https://gotanklesssc.com/" target="_blank" rel="noopener">Go Tankless SC</a>
      </nav>
    </div>
    <div class="foot__bar">
      <p>Licensed · Bonded · Insured · Family Owned &amp; Operated Since 1958</p>
      <p>© <span id="yr">2026</span> Mr. Plumber, Inc. Serving Columbia &amp; the Midlands since 1958.</p>
    </div>
  </div>
</footer>

<a class="fab" href="tel:18036004357" aria-label="Call Mr. Plumber at 803-600-4357">
  """ + PHONE_SVG + """
  <span>Call Now</span>
</a>

<script src="main.js?v=""" + JS_VER + """"></script>
</body>
</html>
"""


def build_page(page, images):
    return "".join([
        head(page), "\n", nav(page["section"]), '\n<main id="main">\n',
        hero(page), intro(page), grid(page, images), industries(page), why(page), cta(page),
        "\n</main>\n", FOOTER,
    ])


def validate(data):
    seen = {}
    for page in data["pages"]:
        for c in page["cards"]:
            pid = c["img"]
            if pid not in data["images"]:
                sys.exit(f"Missing image entry for {pid} ({page['slug']} / {c['title']})")
            if pid in seen:
                sys.exit(f"Image {pid} is used twice: {seen[pid]} and {page['slug']} / {c['title']}")
            seen[pid] = f"{page['slug']} / {c['title']}"
            if not (3 <= len(c["included"]) <= 5 and 2 <= len(c["signs"]) <= 4):
                sys.exit(f"List length out of range on {page['slug']} / {c['title']}")
    text = json.dumps(data, ensure_ascii=False)
    for bad in ("—", "–", "lorem", "$79"):
        if bad in text:
            sys.exit(f"Disallowed text {bad!r} found in data/subpages.json")


def main():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    validate(data)
    for page in data["pages"]:
        out = ROOT / f"{page['slug']}.html"
        out.write_text(build_page(page, data["images"]), encoding="utf-8")
        print(f"wrote {out.name}")


if __name__ == "__main__":
    main()
